/**
 * Dump the app's rig definitions to tools/rig.json, so the Blender script
 * and anything else works from the SAME numbers as the running app. Run
 * it after touching src/armature/rig.ts:
 *
 *   npm run rig:json
 */
import { build } from 'esbuild';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const dir = await mkdtemp(join(tmpdir(), 'bozz-rig-'));
const out = join(dir, 'rig.mjs');
await build({
  entryPoints: ['src/armature/rig.ts'],
  outfile: out,
  bundle: true,
  format: 'esm',
  platform: 'node',
  logLevel: 'warning',
});
const rig = await import(`file://${out}`);
await rm(dir, { recursive: true, force: true });

const presets = rig.RIG_PRESETS.map((p) => rig.rigById(p.id));
const json = {
  note:
    'Generated by tools/dump-rig.mjs from src/armature/rig.ts - do not edit by hand. ' +
    'Units are metres, Y is up and the figure faces +Z (the glTF convention). ' +
    'A bone local Y runs head to tail; local X follows `hint`, the world axis ' +
    'squared up to the bone. Limits are Euler XYZ ranges in degrees on the POSE, ' +
    'on top of the rest orientation; [0, 0] locks an axis.',
  generatedFrom: 'src/armature/rig.ts',
  presets,
};
await writeFile('tools/rig.json', JSON.stringify(json, null, 1) + '\n');
console.log(
  `tools/rig.json: ${presets.length} presets, ${presets.map((p) => `${p.id} (${p.bones.length} bones, ${p.ik.length} chains)`).join(', ')}`,
);
